# Application Name
spring.application.name=order-service

spring.profiles.include=eureka, h2, actuator, logs, swagger

# Initialize database using schema.sql and data.sql
spring.sql.init.mode=always

# --- Server Configuration ---
# Set distinct port for order-service
server.port=8082

# --- Additional Server Settings ---
# Global API context path
server.servlet.context-path=/api/v1
# Enable graceful shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
